databases:
  - name: sushilove-db
    databaseName: sushilove
    user: sushilove
    plan: free

services:
  - type: web
    name: sushilove
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn suwi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sushilove-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
